language: node_js
node_js:
  - "4"
services:
  - mongodb
before_script:
  - sudo /etc/init.d/mongod start
script: "npm install & npm test"
after_script:
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  email: false