language: node_js
node_js:
  - "4"
services:
  - mongodb
env:
  - DB_NAME=us_prices
script: "npm install & npm test"
after_script:
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  email: false
